name: Exercices

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  
on:
  push:
    branches:
        - dev
        - '!staging'
        - 'feat/**'
    paths: 
        - "**.ts"
        - "folder/**"
  pull_request: 
    types: [opened, closed]

  schedule:
    - cron:  '*/5 * * * *'
    - cron:  '* 0/3 * * *'
    - cron:  '30 1/3 * * *'
    - cron:  '* 3 * * 1'

  workflow_dispatch:

    
jobs:
  echo:
    strategy:
      matrix:
        version: [12,14,16]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{matrix.os}}

    defaults:
      run:
        # put the steps in subfolder snapshots
        working-directory: snapshots
    steps:
        - name:
          run: 
            echo "hello world"
  jobTwo:
    if: github.event_name =='push'
    runs-on: ubuntu-latest
  
    steps:
        - name:
          run: 
            echo "hello world"
