name: Install and Build

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  
on:
  push:
    branches:
        - dev
        - '!staging'
        - 'feat/**'
    paths: 
        - "**.ts"
        - "folder/**"
  pull_request: 
    types: [opened, closed]

  schedule:
    - cron:  '*/5 * * * *'
    - cron:  '* 0/3 * * *'
    - cron:  '30 1/3 * * *'
    - cron:  '* 3 * * 1'

    
jobs:
  echo:
    runs-on: ubuntu-latest
  
    steps:
        - name:
          run: 
            echo "hello world"
